CarShowroom/Areas/Admin/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarShowroom.Models;

namespace CarShowroom.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        // GET: DonHang
        public ActionResult Index()
        {
            CarShowroomDbContext DbContext = new CarShowroomDbContext();
            var list = DbContext.HoaDon.ToList();
            return View(list);
        }
        //  Details

        //https://localhost:44353/DonHang/Details/3
        [HttpGet]
        public ActionResult Details(int id)
        {
            CarShowroomDbContext DbContext = new CarShowroomDbContext();
            var list = DbContext.ChiTietHoaDon.Where(p=>p.MaHoaDon == id).ToList();
            return View(list);
        }
    }
}

CarShowroom/Areas/Admin/Views/DonHang/Details.cshtml
@model IEnumerable<CarShowroom.Models.ChiTietHoaDon>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="header-advance-area">
    <div class="header-top-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="header-top-wraper">
                        <div class="row">
                            <div class="col-lg-1 col-md-0 col-sm-1 col-xs-12">
                                <div class="menu-switcher-pro">
                                    <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-7 col-sm-6 col-xs-12">
                                <div class="header-top-menu tabl-d-n">
                                    <ul class="nav navbar-nav mai-top-nav">
                                        <li class="nav-item">
                                            <a href="/Admin/Xe/Index" class="nav-link">Danh Sách Xe</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/Admin/HangXe/Index" class="nav-link">Danh Sách Hãng Xe</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/Admin/KhachHang/Index" class="nav-link">Danh Sách Khách Hàng</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/Admin/DonHang/Index" class="nav-link">Quản lý đơn hàng</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul class="mobile-menu-nav">
                                <li>
                                    <a data-toggle="collapse" data-target="#Charts" href="#">Home <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="index.html">Dashboard v.1</a></li>
                                        <li><a href="index-1.html">Dashboard v.2</a></li>
                                        <li><a href="index-3.html">Dashboard v.3</a></li>
                                        <li><a href="product-list.html">Product List</a></li>
                                        <li><a href="product-edit.html">Product Edit</a></li>
                                        <li><a href="product-detail.html">Product Detail</a></li>
                                        <li><a href="product-cart.html">Product Cart</a></li>
                                        <li><a href="product-payment.html">Product Payment</a></li>
                                        <li><a href="analytics.html">Analytics</a></li>
                                        <li><a href="widgets.html">Widgets</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a data-toggle="collapse" data-target="#demo" href="#">Mailbox <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                                    <ul id="demo" class="collapse dropdown-header-top">
                                        <li>
                                            <a href="mailbox.html">Inbox</a>
                                        </li>
                                        <li>
                                            <a href="mailbox-view.html">View Mail</a>
                                        </li>
                                        <li>
                                            <a href="mailbox-compose.html">Compose Mail</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a data-toggle="collapse" data-target="#others" href="#">Miscellaneous <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                                    <ul id="others" class="collapse dropdown-header-top">
                                        <li><a href="file-manager.html">File Manager</a></li>
                                        <li><a href="contacts.html">Contacts Client</a></li>
                                        <li><a href="projects.html">Project</a></li>
                                        <li><a href="project-details.html">Project Details</a></li>
                                        <li><a href="blog.html">Blog</a></li>
                                        <li><a href="blog-details.html">Blog Details</a></li>
                                        <li><a href="404.html">404 Page</a></li>
                                        <li><a href="500.html">500 Page</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu end -->
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcome-heading">
                                    @using (Html.BeginForm("Index", "HangXe", FormMethod.Get, new { @style = "position:relative" }))
                                    {
                                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, null, new { @style = "color:white; float:left", @class = "form-control", @placeholder = "Tìm kiếm ..." })
                                        <button type="submit" style="float: left; position: absolute; left: 150px;border-radius: 30px" class="btn btn-success">Tìm</button>
                                    }
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="product-status mg-tb-15">
    <div class="container-fluid">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SoLuong)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GhiChu)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ThanhTien)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoLuong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GhiChu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ThanhTien)
                    </td>
                </tr>
            }

        </table>
        <p>
            @Html.ActionLink("Back to List", "Index", "DonHang")
        </p>
    </div>
</div>

CarShowroom/Areas/Admin/Views/DonHang/Index.cshtml
@model IEnumerable<CarShowroom.Models.HoaDon>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="header-advance-area">
    <div class="header-top-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="header-top-wraper">
                        <div class="row">
                            <div class="col-lg-1 col-md-0 col-sm-1 col-xs-12">
                                <div class="menu-switcher-pro">
                                    <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-7 col-sm-6 col-xs-12">
                                <div class="header-top-menu tabl-d-n">
                                    <ul class="nav navbar-nav mai-top-nav">

                                        <li class="nav-item">
                                            <a href="/Admin/Xe/Index" class="nav-link">Danh Sách Xe</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/Admin/HangXe/Index" class="nav-link">Danh Sách Hãng Xe</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/Admin/KhachHang/Index" class="nav-link">Danh Sách Khách Hàng</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/Admin/DonHang/Index" class="nav-link">Quản lý đơn hàng</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul class="mobile-menu-nav">
                                <li>
                                    <a data-toggle="collapse" data-target="#Charts" href="#">Home <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="index.html">Dashboard v.1</a></li>
                                        <li><a href="index-1.html">Dashboard v.2</a></li>
                                        <li><a href="index-3.html">Dashboard v.3</a></li>
                                        <li><a href="product-list.html">Product List</a></li>
                                        <li><a href="product-edit.html">Product Edit</a></li>
                                        <li><a href="product-detail.html">Product Detail</a></li>
                                        <li><a href="product-cart.html">Product Cart</a></li>
                                        <li><a href="product-payment.html">Product Payment</a></li>
                                        <li><a href="analytics.html">Analytics</a></li>
                                        <li><a href="widgets.html">Widgets</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a data-toggle="collapse" data-target="#demo" href="#">Mailbox <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                                    <ul id="demo" class="collapse dropdown-header-top">
                                        <li>
                                            <a href="mailbox.html">Inbox</a>
                                        </li>
                                        <li>
                                            <a href="mailbox-view.html">View Mail</a>
                                        </li>
                                        <li>
                                            <a href="mailbox-compose.html">Compose Mail</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a data-toggle="collapse" data-target="#others" href="#">Miscellaneous <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                                    <ul id="others" class="collapse dropdown-header-top">
                                        <li><a href="file-manager.html">File Manager</a></li>
                                        <li><a href="contacts.html">Contacts Client</a></li>
                                        <li><a href="projects.html">Project</a></li>
                                        <li><a href="project-details.html">Project Details</a></li>
                                        <li><a href="blog.html">Blog</a></li>
                                        <li><a href="blog-details.html">Blog Details</a></li>
                                        <li><a href="404.html">404 Page</a></li>
                                        <li><a href="500.html">500 Page</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu end -->
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcome-heading">
                                    @using (Html.BeginForm("Index", "Xe", FormMethod.Get, new { @style = "position:relative" }))
                                    {
                                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, null, new { @style = "color:white; float:left", @class = "form-control", @placeholder = "Tìm kiếm ..." })
                                        <button type="submit" style="float: left; position: absolute; left: 150px;border-radius: 30px" class="btn btn-success">Tìm</button>
                                    }
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="product-status mg-tb-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>Danh Sách đơn hàng</h4>
                    <div class="add-product">
                      
                    </div>
                    <table>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NgayNhan)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NgayTra)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TongThanhTien)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.GhiChu)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MaKhachHang)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayNhan)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayTra)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TongThanhTien)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GhiChu)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaKhachHang)
                        </td>
                        <td>
                            @Html.ActionLink("Xem Chi Tiết", "Details", new { id = item.MaHoaDon })
                       
                      
                         
                            @Html.ActionLink(", Xóa", "Delete", new { id = item.MaHoaDon })
                      

                        </td>

                    </tr>
                        }



                    </table>
                    <div class="custom-pagination">
                        @*<nav aria-label="Page navigation example">
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                            @Html.PagedListPager(Model, page => Url.Action("Index",
                                new { page, currentFilter = ViewBag.CurrentFilter }))
                        </nav>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CarShowroom/Views/DonHang/Details.cshtml
@model IEnumerable<CarShowroom.Models.ChiTietHoaDon>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Trở về",  "Index", "DonHang")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GhiChu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GhiChu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThanhTien)
        </td>
    </tr>
}

</table>

CarShowroom/Views/DonHang/Index.cshtml
@model IEnumerable<CarShowroom.Models.HoaDon>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Tro ve", "Index", "Home")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NgayNhan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayTra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TongThanhTien)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GhiChu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaKhachHang)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NgayNhan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayTra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TongThanhTien)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GhiChu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaKhachHang)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaHoaDon }) |
            @Html.ActionLink("Chi Tieets hoa don", "Details", new { id=item.MaHoaDon }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaHoaDon })
        </td>
    </tr>
}

</table>